# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CritEval <- function(x0, nlevel, crit) {
    .Call(`_UniDOE_CritEval`, x0, nlevel, crit)
}

SATA_UD <- function(nsamp, nv, nlevel, init_method, initX, crit, maxiter, hits_ratio, levelpermt) {
    .Call(`_UniDOE_SATA_UD`, nsamp, nv, nlevel, init_method, initX, crit, maxiter, hits_ratio, levelpermt)
}

SATA_AUD <- function(xp, nnew, nv, nlevel, init_method, initX, crit, maxiter, hits_ratio, levelpermt) {
    .Call(`_UniDOE_SATA_AUD`, xp, nnew, nv, nlevel, init_method, initX, crit, maxiter, hits_ratio, levelpermt)
}

SATA_AUD_COL <- function(xp, nvnew, nlevel, init_method, initX, crit, maxiter, hits_ratio, levelpermt) {
    .Call(`_UniDOE_SATA_AUD_COL`, xp, nvnew, nlevel, init_method, initX, crit, maxiter, hits_ratio, levelpermt)
}

